export const JURISDICTIONS = {
  US: {
    code: "US",
    name: "United States",
    legalSystem: "Common Law",
    terminology: {
      contract: "Agreement",
      breach: "Breach of Contract",
      damages: "Compensatory Damages",
      termination: "Termination Clause",
      indemnification: "Indemnification",
      governing_law: "Governing Law",
    },
    complianceNotes: [
      "Must comply with UCC for commercial transactions",
      "State-specific contract laws may apply",
      "Federal regulations for specific industries",
      "Consumer protection laws vary by state",
    ],
  },
  IN: {
    code: "IN",
    name: "India",
    legalSystem: "Common Law (Indian Contract Act 1872)",
    terminology: {
      contract: "Agreement",
      breach: "Breach of Contract (Section 73)",
      damages: "Compensation for Breach",
      termination: "Termination Clause",
      indemnification: "Indemnity (Section 124)",
      governing_law: "Applicable Law",
    },
    complianceNotes: [
      "Must comply with Indian Contract Act 1872",
      "Stamp duty requirements vary by state",
      "Specific Performance under Specific Relief Act",
      "Consumer Protection Act 2019 applies",
      "Information Technology Act for digital contracts",
    ],
  },
  UK: {
    code: "UK",
    name: "United Kingdom",
    legalSystem: "Common Law (English Contract Law)",
    terminology: {
      contract: "Contract / Deed",
      breach: "Breach of Contract",
      damages: "Damages",
      termination: "Termination Provisions",
      indemnification: "Indemnity",
      governing_law: "Governing Law and Jurisdiction",
    },
    complianceNotes: [
      "Must comply with English Contract Law principles",
      "Consumer Rights Act 2015 for B2C contracts",
      "Unfair Contract Terms Act 1977",
      "UK GDPR for data processing clauses",
      "Late Payment of Commercial Debts regulations",
    ],
  },
} as const;

export type JurisdictionCode = keyof typeof JURISDICTIONS;

export const CONTRACT_TYPES = [
  "Service Agreement",
  "Non-Disclosure Agreement",
  "Employment Contract",
  "Software License Agreement",
  "Partnership Agreement",
  "Lease Agreement",
  "Sales Agreement",
  "Consulting Agreement",
  "Master Service Agreement",
  "Statement of Work",
  "Terms of Service",
  "Privacy Policy",
  "Vendor Agreement",
  "Distribution Agreement",
  "Joint Venture Agreement",
] as const;

export const CLAUSE_CATEGORIES = [
  "Payment Terms",
  "Termination",
  "Liability",
  "Indemnification",
  "Confidentiality",
  "Intellectual Property",
  "Dispute Resolution",
  "Force Majeure",
  "Governing Law",
  "Assignment",
  "Warranty",
  "Representations",
  "Non-Compete",
  "Non-Solicitation",
  "Data Protection",
  "Insurance",
  "Compliance",
  "Amendment",
  "Entire Agreement",
  "Severability",
  "Notices",
  "General",
] as const;
